### PR TITLE
Remove duplicated unicodeRanges

### PR DESCRIPTION
**Pull request by moyogo**
There are two custom parameters unicodeRanges in Junicode-widths.glyphspackage.
This keeps the larger one and removes the shorter one.

### CODE REVIEW

**Comment by psb1558** [comment]
Good God, how did *that* happen? Thanks again, Denis!

**Comment by psb1558** [comment]
This merge is being blocked by a conflict that I don't understand (e.g. what is going on with FontProof/fontproof? Why does it have anything to do with this?). Can you make sense of it? (Or maybe I should just delete that custom parameter myself).

**Comment by psb1558** [comment]
Never mind. It seems to have happened . . . somehow.

I do not grok PRs.

**Comment by moyogo** [comment]
The issue seems to be about an OTF not being there:
https://github.com/psb1558/Junicode-font/actions/runs/5900065814/job/16003616340#step:4:8

**Comment by alerque** [comment]
There are twe completely unrelated things going on here. FontProof is failing to run in CI (we can look into that) but that has nothing at all to do with the merge conflict. The merge conflict is because the same lines of the same file were edited since the one this PR is based on was branched. That will need to be resolved, (probably easiest to do by hand but could also be done by checking out this branch, then checking out just the original file from the master branch, then redoing the change).

**Comment by psb1558** [comment]
Okay, thanks guys. But this doesn't need to be done as a PR since the change is so simple—it's far easier just to do it than to investigate and resolve the conflict.

I would like to get FontProof running. I did some testing of font features and axes with LuaTeX, but it would be good to go forward with a tool that's made for the task.

**Pull request merged**
